AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  agri_chat

Parameters:
  SecretKey:
    Type: String
    Description: Secret key for the jwt
    NoEcho: true

  OpenAIKey:
    Type: String
    Description: OpenAI API key
    NoEcho: true

Globals:
  Function:
    Timeout: 20
    Runtime: python3.9
    CodeUri: agri_chat/
    MemorySize: 256
    Architectures:
      - x86_64
    Layers:
      - !Ref DependenciesLayer
    Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
          OPENAI_API_KEY: !Ref OpenAIKey
Resources:
  BackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Methods: "'*'"
      Auth:
        DefaultAuthorizer: !GetAtt AuthorizerFunction.Arn

  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FormsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Forms
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
  MessagesTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Messages
      AttributeDefinitions:
        - AttributeName: owner
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: owner
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: agri-chat-dependencies
      Description: Dependencies for agri_chat
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9
      BuildArchitecture: x86_64
  
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: authorizer-function
      Handler: handlers/authorization.authorizer

  ChatGPTFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chat-gpt-function
      Handler: handlers/chat_gpt.chat_gpt
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /chat_gpt
            Method: GET
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: MessagesTable
          Permissions:
            - Write
            - Read

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: register-function
      Handler: handlers/authentication.register
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /register
            Method: POST
            Auth:
              Authorizer: NONE
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: MyDynamoDBTable
          Permissions:
            - Write
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: login-function
      Handler: handlers/authentication.login
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /login
            Method: POST
            Auth:
              Authorizer: NONE
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: MyDynamoDBTable
          Permissions:
            - Write
            - Read

  CreateFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-form-function
      Handler: handlers/forms.create_form
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /forms
            Method: POST
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FormsTable
          Permissions:
            - Write
  
  GetFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-form-function
      Handler: handlers/forms.get_form
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /forms/{id}
            Method: GET
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FormsTable
          Permissions:
            - Read
  
  ListFormsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-forms-function
      Handler: handlers/forms.list_forms
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /forms
            Method: GET
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FormsTable
          Permissions:
            - Read
  
  DeleteFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete-form-function
      Handler: handlers/forms.delete_form
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /forms/{id}
            Method: DELETE
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FormsTable
          Permissions:
            - Write
            - Read

  UpdateFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-form-function
      Handler: handlers/forms.update_form
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /forms/{id}
            Method: PATCH
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: FormsTable
          Permissions:
            - Write
            - Read