AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  agri_chat

Globals:
  Function:
    Timeout: 20
    Runtime: python3.9
    CodeUri: agri_chat/
    MemorySize: 256
    Architectures:
      - x86_64
    Layers:
      - !Ref DependenciesLayer

Resources:
  BackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Methods: "'*'"
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: agri-chat-dependencies
      Description: Dependencies for agri_chat
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
  ChatGPTFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.app.lambda_handler
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /hello
            Method: get

